# Generated by Django 3.2.9 on 2021-11-11 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('actual_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('check_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Scrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scrapper.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='price_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.producthistory'),
        ),
    ]
